#!/bin/bash
~/elm.2 make src/Framework.elm --output docs/build/019-framework.js --optimize
uglifyjs --output docs/build/019-framework-min.js docs/build/019-framework.js --mangle --toplevel --compress
