#!/bin/bash
rm -rf elm-stuff ; rm ~/.elm/0.19.0/package/*/*/*/*.dat ; time ~/elm make src/Framework.elm
# ./elm make src/Framework.elm --output docs/build/019-framework.js
# elm-live --output=docs/build/framework.js src/Framework.elm --dir=docs --debug --port=8000
