#!/bin/bash
#elm make src/Framework.elm                                      --output=docs/js-compiled/framework.js --optimize
#elm make examples/exampleCustomized/src/FrameworkCustomized.elm --output=docs/js-compiled/frameworkCustomized.js --optimize

# uglifyjs --output docs/build/framework-min.js docs/build/framework.js --mangle --toplevel --compress
# uglifyjs docs/build/framework.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output docs/build/framework-min.js
